### ISSUE TITLE
Feature Request : direct access to the IP page in the web view

### ISSUE THREAD

**Issue by Te-k** [binaryedge/40fy#12]
Hi,

Just a suggestion of improvement in the web interface : when I am searching for an IP in https://app.binaryedge.io/services/query, I get a list of results for this related IP which is not what I am looking for, I am looking for the page with all the details about this IP (like https://app.binaryedge.io/services/query/8.8.8.8). This result page is really helpful when searching for a keyword / tag / complex search, but not for an IP, and half of my searchs in BE are details about an IP. Would it be possible to have a check server side for the IP address format and redirect to the IP page directly if it is an IP ?

What do you think ?

**Comment by balgan** [comment]
This has been added! Thanks @Te-k !
