### ISSUE TITLE
DNS Information

### ISSUE THREAD

**Issue by balgan** [binaryedge/40fy#6]
This feature allows you as a user to provide an ip address and in return receive a list of websites potentially hosted on that ip address:
For example for the ip address: 213.13.146.142
you would see the following data:

[{"A": ["213.13.146.142"], "subdomain": "www", "created_at": "2018-01-21T14:23:00.397489", "root": "sapo.pt", "title": "SAPO", "name": "sapo", "domain": "www.sapo.pt", "AAAA": ["2001:8a0:2102:c:213:13:146:142"], "suffix": "pt", "updated_at": "2018-06-12T21:40:56.463209", "org": "MEO Servicos de Comunicacoes e Multimedia SA"}, {"A": ["213.13.146.142"], "subdomain": "", "created_at": "2018-09-21T06:01:01.647817", "root": "sapo.pt", "name": "sapo", "domain": "sapo.pt", "suffix": "pt", "updated_at": "2018-09-21T06:01:01.647817"}]

**Comment by igama** [comment]
Example return for the DNS endpoint

This will include, if available:

- A
- AAAA
- CNAME
- MX
- NS

```
{"query": "root:example.com", "page": 1, "pagesize": 100, "total": 6308, "events": [{"updated_at": "2018-01-10T20:54:44.202758", "domain": "m.example.com", "root": "example.com"}, {"A": ["92.63.97.42"], "updated_at": "2018-09-22T04:53:21.082802", "domain": "startup.antichat.example.com", "root": "example.com"}, {"A": ["92.63.195.2"], "updated_at": "2018-09-22T04:18:52.330126", "domain": "anandop1.example.com", "root": "example.com"}, {"A": ["91.235.136.112"], "updated_at": "2018-09-22T04:14:29.031596", "domain": "vladimirbezz3.example.com", "root": "example.com"}, {"A": ["93.179.68.6"], "updated_at": "2018-09-22T03:51:36.852124", "domain": "i.seeva.example.com", "root": "example.com"}, {"A": ["188.120.255.132"], "updated_at": "2018-09-22T09:55:12.914372", "domain": "al.example.com", "root": "example.com"}, {"A": ["185.180.231.51"], "updated_at": "2018-09-22T09:51:19.612413", "domain": "misha198815.example.com", "root": "example.com"}, {"A": ["185.219.80.42"], "updated_at": "2018-09-22T09:53:24.306640", "domain": "ucbnjyarocqt1ytlbm.example.com", "root": "example.com"}, {"A": ["93.179.68.111"], "updated_at": "2018-09-22T09:20:33.058506", "domain": "antonovaatim.example.com", "root": "example.com"}, {"A": ["92.223.105.199"], "updated_at": "2018-09-22T09:24:17.900861", "domain": "alexeypolyashov.example.com", "root": "example.com"}]}
```

**Comment by balgan** [comment]
Implemented. Closing this.
