### ISSUE TITLE
Hash of webpages

### ISSUE THREAD

**Issue by Te-k** [binaryedge/40fy#7]
In some cases, it is really helpful to search for web pages with a specific hash. It would be great to have this feature in Binary Edge (sha256 maybe ?)

**Comment by balgan** [comment]
Added! Thanks!

**Comment by thomasdullien** [comment]
Hey there,

not sure if this is a good idea, but one of the downsides of SHA256 is that it is always going to be unique. Calculating a simhash over the website would allow similarity searches, too ... :-)
